<?php

namespace OC\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends EntityRepository
{
	public function getApplicationsWithAdvert($limit)
	{
		$qb = $this->createQuerybuilder('app');
		$qb->join('app.advert', 'a')
		   ->addSelect('a');
		
		$qb->setMaxResults($limit);
		
		return $qb->getQuery()->getResult();
	}
}
